template = ""
rev_id = 4
template_sha = "156a8b834dacf74fc905a1ee460fe5eabb9556c6"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "de"
__UND2C_TRG__ = "myv"
__UNDEFINED_SOURCE__ = "German"
__UNDEFINED_TARGET__ = "Erzya"
__UND_SRC__ = "deu"
__UND_TRG__ = "myv"
